name: health_app # 프로젝트 이름 (보통 폴더 이름과 동일)
description: A new Flutter project. # 프로젝트 설명
publish_to: 'none' # 패키지를 pub.dev에 게시하지 않으려면 'none'으로 설정

version: 1.0.0+1 # 앱 버전 (version+build number)

environment:
  sdk: '>=3.0.0 <4.0.0' # Flutter SDK 버전 제약 조건

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  http: ^1.2.2

  # 여기에 외부 패키지를 추가합니다. 예:
  # shared_preferences: ^2.0.15  # ^는 호환되는 최신 버전을 의미
  # http: ^1.1.0
  # provider: ^6.0.5

  cupertino_icons: ^1.0.2 # iOS 스타일 아이콘 (기본 포함)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # 코드 스타일 및 잠재적 오류 검사를 위한 린트 규칙

flutter:
  uses-material-design: true # Material Design 사용 여부

  # 애셋(이미지, 폰트 등)을 추가하려면 여기에 경로를 지정합니다.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 폰트를 추가하려면 여기에 지정합니다.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700